version: "3"
services:
  react-app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_NAME=Bartu-dev
      - CHOKIDAR_USEPOLLING=true