# STAGE 1
FROM node as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .
ARG REACT_APP_NAME
ENV REACT_APP_NAME=$REACT_APP_NAME

# Only difference is here
CMD npm run build

# STAGE 2
FROM nginx

# Copy the output of the -npm run build-
COPY --from=build /app/build /usr/share/nginx/html